/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/spanner.proto

package com.google.spanner.v1;

/**
 *
 *
 * <pre>
 * The request for [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction].
 * </pre>
 *
 * Protobuf type {@code google.spanner.v1.BeginTransactionRequest}
 */
public final class BeginTransactionRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.spanner.v1.BeginTransactionRequest)
    BeginTransactionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use BeginTransactionRequest.newBuilder() to construct.
  private BeginTransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private BeginTransactionRequest() {
    session_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new BeginTransactionRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private BeginTransactionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
          case 18:
            {
              TransactionOptions.Builder subBuilder = null;
              if (options_ != null) {
                subBuilder = options_.toBuilder();
              }
              options_ = input.readMessage(TransactionOptions.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(options_);
                options_ = subBuilder.buildPartial();
              }

              break;
            }
          case 26:
            {
              RequestOptions.Builder subBuilder = null;
              if (requestOptions_ != null) {
                subBuilder = requestOptions_.toBuilder();
              }
              requestOptions_ = input.readMessage(RequestOptions.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(requestOptions_);
                requestOptions_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return SpannerProto.internal_static_google_spanner_v1_BeginTransactionRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return SpannerProto.internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(BeginTransactionRequest.class, Builder.class);
  }

  public static final int SESSION_FIELD_NUMBER = 1;
  private volatile Object session_;
  /**
   *
   *
   * <pre>
   * Required. The session in which the transaction runs.
   * </pre>
   *
   * <code>
   * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The session.
   */
  @Override
  public String getSession() {
    Object ref = session_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      session_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. The session in which the transaction runs.
   * </pre>
   *
   * <code>
   * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for session.
   */
  @Override
  public com.google.protobuf.ByteString getSessionBytes() {
    Object ref = session_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      session_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  private TransactionOptions options_;
  /**
   *
   *
   * <pre>
   * Required. Options for the new transaction.
   * </pre>
   *
   * <code>
   * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the options field is set.
   */
  @Override
  public boolean hasOptions() {
    return options_ != null;
  }
  /**
   *
   *
   * <pre>
   * Required. Options for the new transaction.
   * </pre>
   *
   * <code>
   * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The options.
   */
  @Override
  public TransactionOptions getOptions() {
    return options_ == null ? TransactionOptions.getDefaultInstance() : options_;
  }
  /**
   *
   *
   * <pre>
   * Required. Options for the new transaction.
   * </pre>
   *
   * <code>
   * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  @Override
  public TransactionOptionsOrBuilder getOptionsOrBuilder() {
    return getOptions();
  }

  public static final int REQUEST_OPTIONS_FIELD_NUMBER = 3;
  private RequestOptions requestOptions_;
  /**
   *
   *
   * <pre>
   * Common options for this request.
   * Priority is ignored for this request. Setting the priority in this
   * request_options struct will not do anything. To set the priority for a
   * transaction, set it on the reads and writes that are part of this
   * transaction instead.
   * </pre>
   *
   * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
   *
   * @return Whether the requestOptions field is set.
   */
  @Override
  public boolean hasRequestOptions() {
    return requestOptions_ != null;
  }
  /**
   *
   *
   * <pre>
   * Common options for this request.
   * Priority is ignored for this request. Setting the priority in this
   * request_options struct will not do anything. To set the priority for a
   * transaction, set it on the reads and writes that are part of this
   * transaction instead.
   * </pre>
   *
   * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
   *
   * @return The requestOptions.
   */
  @Override
  public RequestOptions getRequestOptions() {
    return requestOptions_ == null ? RequestOptions.getDefaultInstance() : requestOptions_;
  }
  /**
   *
   *
   * <pre>
   * Common options for this request.
   * Priority is ignored for this request. Setting the priority in this
   * request_options struct will not do anything. To set the priority for a
   * transaction, set it on the reads and writes that are part of this
   * transaction instead.
   * </pre>
   *
   * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
   */
  @Override
  public RequestOptionsOrBuilder getRequestOptionsOrBuilder() {
    return getRequestOptions();
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getSessionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, session_);
    }
    if (options_ != null) {
      output.writeMessage(2, getOptions());
    }
    if (requestOptions_ != null) {
      output.writeMessage(3, getRequestOptions());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, session_);
    }
    if (options_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getOptions());
    }
    if (requestOptions_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getRequestOptions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof BeginTransactionRequest)) {
      return super.equals(obj);
    }
    BeginTransactionRequest other = (BeginTransactionRequest) obj;

    if (!getSession().equals(other.getSession())) return false;
    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions().equals(other.getOptions())) return false;
    }
    if (hasRequestOptions() != other.hasRequestOptions()) return false;
    if (hasRequestOptions()) {
      if (!getRequestOptions().equals(other.getRequestOptions())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_FIELD_NUMBER;
    hash = (53 * hash) + getSession().hashCode();
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    if (hasRequestOptions()) {
      hash = (37 * hash) + REQUEST_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestOptions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BeginTransactionRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BeginTransactionRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BeginTransactionRequest parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BeginTransactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BeginTransactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BeginTransactionRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BeginTransactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static BeginTransactionRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static BeginTransactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static BeginTransactionRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static BeginTransactionRequest parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static BeginTransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(BeginTransactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * The request for [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction].
   * </pre>
   *
   * Protobuf type {@code google.spanner.v1.BeginTransactionRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.spanner.v1.BeginTransactionRequest)
      BeginTransactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return SpannerProto.internal_static_google_spanner_v1_BeginTransactionRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return SpannerProto
          .internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(BeginTransactionRequest.class, Builder.class);
    }

    // Construct using com.google.spanner.v1.BeginTransactionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      session_ = "";

      if (optionsBuilder_ == null) {
        options_ = null;
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }
      if (requestOptionsBuilder_ == null) {
        requestOptions_ = null;
      } else {
        requestOptions_ = null;
        requestOptionsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return SpannerProto.internal_static_google_spanner_v1_BeginTransactionRequest_descriptor;
    }

    @Override
    public BeginTransactionRequest getDefaultInstanceForType() {
      return BeginTransactionRequest.getDefaultInstance();
    }

    @Override
    public BeginTransactionRequest build() {
      BeginTransactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BeginTransactionRequest buildPartial() {
      BeginTransactionRequest result = new BeginTransactionRequest(this);
      result.session_ = session_;
      if (optionsBuilder_ == null) {
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      if (requestOptionsBuilder_ == null) {
        result.requestOptions_ = requestOptions_;
      } else {
        result.requestOptions_ = requestOptionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BeginTransactionRequest) {
        return mergeFrom((BeginTransactionRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BeginTransactionRequest other) {
      if (other == BeginTransactionRequest.getDefaultInstance()) return this;
      if (!other.getSession().isEmpty()) {
        session_ = other.session_;
        onChanged();
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      if (other.hasRequestOptions()) {
        mergeRequestOptions(other.getRequestOptions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BeginTransactionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BeginTransactionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object session_ = "";
    /**
     *
     *
     * <pre>
     * Required. The session in which the transaction runs.
     * </pre>
     *
     * <code>
     * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The session.
     */
    public String getSession() {
      Object ref = session_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. The session in which the transaction runs.
     * </pre>
     *
     * <code>
     * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The bytes for session.
     */
    public com.google.protobuf.ByteString getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. The session in which the transaction runs.
     * </pre>
     *
     * <code>
     * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The session to set.
     * @return This builder for chaining.
     */
    public Builder setSession(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      session_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. The session in which the transaction runs.
     * </pre>
     *
     * <code>
     * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSession() {

      session_ = getDefaultInstance().getSession();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. The session in which the transaction runs.
     * </pre>
     *
     * <code>
     * string session = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The bytes for session to set.
     * @return This builder for chaining.
     */
    public Builder setSessionBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      session_ = value;
      onChanged();
      return this;
    }

    private TransactionOptions options_;
    private com.google.protobuf.SingleFieldBuilderV3<
            TransactionOptions, TransactionOptions.Builder, TransactionOptionsOrBuilder>
        optionsBuilder_;
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     *
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return optionsBuilder_ != null || options_ != null;
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     *
     * @return The options.
     */
    public TransactionOptions getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? TransactionOptions.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public Builder setOptions(TransactionOptions value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
        onChanged();
      } else {
        optionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public Builder setOptions(TransactionOptions.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
        onChanged();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public Builder mergeOptions(TransactionOptions value) {
      if (optionsBuilder_ == null) {
        if (options_ != null) {
          options_ = TransactionOptions.newBuilder(options_).mergeFrom(value).buildPartial();
        } else {
          options_ = value;
        }
        onChanged();
      } else {
        optionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = null;
        onChanged();
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public TransactionOptions.Builder getOptionsBuilder() {

      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    public TransactionOptionsOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ? TransactionOptions.getDefaultInstance() : options_;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Options for the new transaction.
     * </pre>
     *
     * <code>
     * .google.spanner.v1.TransactionOptions options = 2 [(.google.api.field_behavior) = REQUIRED];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            TransactionOptions, TransactionOptions.Builder, TransactionOptionsOrBuilder>
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                TransactionOptions, TransactionOptions.Builder, TransactionOptionsOrBuilder>(
                getOptions(), getParentForChildren(), isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private RequestOptions requestOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
            RequestOptions, RequestOptions.Builder, RequestOptionsOrBuilder>
        requestOptionsBuilder_;
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     *
     * @return Whether the requestOptions field is set.
     */
    public boolean hasRequestOptions() {
      return requestOptionsBuilder_ != null || requestOptions_ != null;
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     *
     * @return The requestOptions.
     */
    public RequestOptions getRequestOptions() {
      if (requestOptionsBuilder_ == null) {
        return requestOptions_ == null ? RequestOptions.getDefaultInstance() : requestOptions_;
      } else {
        return requestOptionsBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public Builder setRequestOptions(RequestOptions value) {
      if (requestOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestOptions_ = value;
        onChanged();
      } else {
        requestOptionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public Builder setRequestOptions(RequestOptions.Builder builderForValue) {
      if (requestOptionsBuilder_ == null) {
        requestOptions_ = builderForValue.build();
        onChanged();
      } else {
        requestOptionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public Builder mergeRequestOptions(RequestOptions value) {
      if (requestOptionsBuilder_ == null) {
        if (requestOptions_ != null) {
          requestOptions_ =
              RequestOptions.newBuilder(requestOptions_).mergeFrom(value).buildPartial();
        } else {
          requestOptions_ = value;
        }
        onChanged();
      } else {
        requestOptionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public Builder clearRequestOptions() {
      if (requestOptionsBuilder_ == null) {
        requestOptions_ = null;
        onChanged();
      } else {
        requestOptions_ = null;
        requestOptionsBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public RequestOptions.Builder getRequestOptionsBuilder() {

      onChanged();
      return getRequestOptionsFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    public RequestOptionsOrBuilder getRequestOptionsOrBuilder() {
      if (requestOptionsBuilder_ != null) {
        return requestOptionsBuilder_.getMessageOrBuilder();
      } else {
        return requestOptions_ == null ? RequestOptions.getDefaultInstance() : requestOptions_;
      }
    }
    /**
     *
     *
     * <pre>
     * Common options for this request.
     * Priority is ignored for this request. Setting the priority in this
     * request_options struct will not do anything. To set the priority for a
     * transaction, set it on the reads and writes that are part of this
     * transaction instead.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions request_options = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            RequestOptions, RequestOptions.Builder, RequestOptionsOrBuilder>
        getRequestOptionsFieldBuilder() {
      if (requestOptionsBuilder_ == null) {
        requestOptionsBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                RequestOptions, RequestOptions.Builder, RequestOptionsOrBuilder>(
                getRequestOptions(), getParentForChildren(), isClean());
        requestOptions_ = null;
      }
      return requestOptionsBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.spanner.v1.BeginTransactionRequest)
  }

  // @@protoc_insertion_point(class_scope:google.spanner.v1.BeginTransactionRequest)
  private static final BeginTransactionRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new BeginTransactionRequest();
  }

  public static BeginTransactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeginTransactionRequest> PARSER =
      new com.google.protobuf.AbstractParser<BeginTransactionRequest>() {
        @Override
        public BeginTransactionRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BeginTransactionRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<BeginTransactionRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BeginTransactionRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public BeginTransactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
