/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/spanner.proto

package com.google.spanner.v1;

/**
 *
 *
 * <pre>
 * Common request options for various APIs.
 * </pre>
 *
 * Protobuf type {@code google.spanner.v1.RequestOptions}
 */
public final class RequestOptions extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.spanner.v1.RequestOptions)
    RequestOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use RequestOptions.newBuilder() to construct.
  private RequestOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private RequestOptions() {
    priority_ = 0;
    requestTag_ = "";
    transactionTag_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new RequestOptions();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private RequestOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8:
            {
              int rawValue = input.readEnum();

              priority_ = rawValue;
              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              requestTag_ = s;
              break;
            }
          case 26:
            {
              String s = input.readStringRequireUtf8();

              transactionTag_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return SpannerProto.internal_static_google_spanner_v1_RequestOptions_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return SpannerProto.internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(RequestOptions.class, Builder.class);
  }

  /**
   *
   *
   * <pre>
   * The relative priority for requests. Note that priority is not applicable
   * for BeginTransaction.
   * </pre>
   *
   * Protobuf enum {@code google.spanner.v1.RequestOptions.Priority}
   */
  public enum Priority implements com.google.protobuf.ProtocolMessageEnum {
    /**
     *
     *
     * <pre>
     * PRIORITY_UNSPECIFIED is equivalent to PRIORITY_HIGH.
     * </pre>
     *
     * <code>PRIORITY_UNSPECIFIED = 0;</code>
     */
    PRIORITY_UNSPECIFIED(0),
    /**
     *
     *
     * <pre>
     * This specifies that the request is low priority.
     * </pre>
     *
     * <code>PRIORITY_LOW = 1;</code>
     */
    PRIORITY_LOW(1),
    /**
     *
     *
     * <pre>
     * This specifies that the request is medium priority.
     * </pre>
     *
     * <code>PRIORITY_MEDIUM = 2;</code>
     */
    PRIORITY_MEDIUM(2),
    /**
     *
     *
     * <pre>
     * This specifies that the request is high priority.
     * </pre>
     *
     * <code>PRIORITY_HIGH = 3;</code>
     */
    PRIORITY_HIGH(3),
    UNRECOGNIZED(-1),
    ;

    /**
     *
     *
     * <pre>
     * PRIORITY_UNSPECIFIED is equivalent to PRIORITY_HIGH.
     * </pre>
     *
     * <code>PRIORITY_UNSPECIFIED = 0;</code>
     */
    public static final int PRIORITY_UNSPECIFIED_VALUE = 0;
    /**
     *
     *
     * <pre>
     * This specifies that the request is low priority.
     * </pre>
     *
     * <code>PRIORITY_LOW = 1;</code>
     */
    public static final int PRIORITY_LOW_VALUE = 1;
    /**
     *
     *
     * <pre>
     * This specifies that the request is medium priority.
     * </pre>
     *
     * <code>PRIORITY_MEDIUM = 2;</code>
     */
    public static final int PRIORITY_MEDIUM_VALUE = 2;
    /**
     *
     *
     * <pre>
     * This specifies that the request is high priority.
     * </pre>
     *
     * <code>PRIORITY_HIGH = 3;</code>
     */
    public static final int PRIORITY_HIGH_VALUE = 3;

    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException("Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Priority valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Priority forNumber(int value) {
      switch (value) {
        case 0:
          return PRIORITY_UNSPECIFIED;
        case 1:
          return PRIORITY_LOW;
        case 2:
          return PRIORITY_MEDIUM;
        case 3:
          return PRIORITY_HIGH;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Priority> internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<Priority> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
          public Priority findValueByNumber(int number) {
            return Priority.forNumber(number);
          }
        };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
      return RequestOptions.getDescriptor().getEnumTypes().get(0);
    }

    private static final Priority[] VALUES = values();

    public static Priority valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Priority(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.spanner.v1.RequestOptions.Priority)
  }

  public static final int PRIORITY_FIELD_NUMBER = 1;
  private int priority_;
  /**
   *
   *
   * <pre>
   * Priority for the request.
   * </pre>
   *
   * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
   *
   * @return The enum numeric value on the wire for priority.
   */
  @Override
  public int getPriorityValue() {
    return priority_;
  }
  /**
   *
   *
   * <pre>
   * Priority for the request.
   * </pre>
   *
   * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
   *
   * @return The priority.
   */
  @Override
  public Priority getPriority() {
    @SuppressWarnings("deprecation")
    Priority result = Priority.valueOf(priority_);
    return result == null ? Priority.UNRECOGNIZED : result;
  }

  public static final int REQUEST_TAG_FIELD_NUMBER = 2;
  private volatile Object requestTag_;
  /**
   *
   *
   * <pre>
   * A per-request tag which can be applied to queries or reads, used for
   * statistics collection.
   * Both request_tag and transaction_tag can be specified for a read or query
   * that belongs to a transaction.
   * This field is ignored for requests where it's not applicable (e.g.
   * CommitRequest).
   * `request_tag` must be a valid identifier of the form:
   * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
   * </pre>
   *
   * <code>string request_tag = 2;</code>
   *
   * @return The requestTag.
   */
  @Override
  public String getRequestTag() {
    Object ref = requestTag_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      requestTag_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * A per-request tag which can be applied to queries or reads, used for
   * statistics collection.
   * Both request_tag and transaction_tag can be specified for a read or query
   * that belongs to a transaction.
   * This field is ignored for requests where it's not applicable (e.g.
   * CommitRequest).
   * `request_tag` must be a valid identifier of the form:
   * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
   * </pre>
   *
   * <code>string request_tag = 2;</code>
   *
   * @return The bytes for requestTag.
   */
  @Override
  public com.google.protobuf.ByteString getRequestTagBytes() {
    Object ref = requestTag_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      requestTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_TAG_FIELD_NUMBER = 3;
  private volatile Object transactionTag_;
  /**
   *
   *
   * <pre>
   * A tag used for statistics collection about this transaction.
   * Both request_tag and transaction_tag can be specified for a read or query
   * that belongs to a transaction.
   * The value of transaction_tag should be the same for all requests belonging
   * to the same transaction.
   * If this request doesn’t belong to any transaction, transaction_tag will be
   * ignored.
   * `transaction_tag` must be a valid identifier of the format:
   * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
   * </pre>
   *
   * <code>string transaction_tag = 3;</code>
   *
   * @return The transactionTag.
   */
  @Override
  public String getTransactionTag() {
    Object ref = transactionTag_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transactionTag_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * A tag used for statistics collection about this transaction.
   * Both request_tag and transaction_tag can be specified for a read or query
   * that belongs to a transaction.
   * The value of transaction_tag should be the same for all requests belonging
   * to the same transaction.
   * If this request doesn’t belong to any transaction, transaction_tag will be
   * ignored.
   * `transaction_tag` must be a valid identifier of the format:
   * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
   * </pre>
   *
   * <code>string transaction_tag = 3;</code>
   *
   * @return The bytes for transactionTag.
   */
  @Override
  public com.google.protobuf.ByteString getTransactionTagBytes() {
    Object ref = transactionTag_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      transactionTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (priority_ != Priority.PRIORITY_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, priority_);
    }
    if (!getRequestTagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestTag_);
    }
    if (!getTransactionTagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transactionTag_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (priority_ != Priority.PRIORITY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, priority_);
    }
    if (!getRequestTagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestTag_);
    }
    if (!getTransactionTagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transactionTag_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof RequestOptions)) {
      return super.equals(obj);
    }
    RequestOptions other = (RequestOptions) obj;

    if (priority_ != other.priority_) return false;
    if (!getRequestTag().equals(other.getRequestTag())) return false;
    if (!getTransactionTag().equals(other.getTransactionTag())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + priority_;
    hash = (37 * hash) + REQUEST_TAG_FIELD_NUMBER;
    hash = (53 * hash) + getRequestTag().hashCode();
    hash = (37 * hash) + TRANSACTION_TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionTag().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RequestOptions parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static RequestOptions parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static RequestOptions parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static RequestOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static RequestOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static RequestOptions parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static RequestOptions parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static RequestOptions parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static RequestOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static RequestOptions parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static RequestOptions parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static RequestOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(RequestOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Common request options for various APIs.
   * </pre>
   *
   * Protobuf type {@code google.spanner.v1.RequestOptions}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.spanner.v1.RequestOptions)
      RequestOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return SpannerProto.internal_static_google_spanner_v1_RequestOptions_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return SpannerProto.internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(RequestOptions.class, Builder.class);
    }

    // Construct using com.google.spanner.v1.RequestOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      priority_ = 0;

      requestTag_ = "";

      transactionTag_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return SpannerProto.internal_static_google_spanner_v1_RequestOptions_descriptor;
    }

    @Override
    public RequestOptions getDefaultInstanceForType() {
      return RequestOptions.getDefaultInstance();
    }

    @Override
    public RequestOptions build() {
      RequestOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RequestOptions buildPartial() {
      RequestOptions result = new RequestOptions(this);
      result.priority_ = priority_;
      result.requestTag_ = requestTag_;
      result.transactionTag_ = transactionTag_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestOptions) {
        return mergeFrom((RequestOptions) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestOptions other) {
      if (other == RequestOptions.getDefaultInstance()) return this;
      if (other.priority_ != 0) {
        setPriorityValue(other.getPriorityValue());
      }
      if (!other.getRequestTag().isEmpty()) {
        requestTag_ = other.requestTag_;
        onChanged();
      }
      if (!other.getTransactionTag().isEmpty()) {
        transactionTag_ = other.transactionTag_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int priority_ = 0;
    /**
     *
     *
     * <pre>
     * Priority for the request.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
     *
     * @return The enum numeric value on the wire for priority.
     */
    @Override
    public int getPriorityValue() {
      return priority_;
    }
    /**
     *
     *
     * <pre>
     * Priority for the request.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
     *
     * @param value The enum numeric value on the wire for priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriorityValue(int value) {

      priority_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Priority for the request.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
     *
     * @return The priority.
     */
    @Override
    public Priority getPriority() {
      @SuppressWarnings("deprecation")
      Priority result = Priority.valueOf(priority_);
      return result == null ? Priority.UNRECOGNIZED : result;
    }
    /**
     *
     *
     * <pre>
     * Priority for the request.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
     *
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(Priority value) {
      if (value == null) {
        throw new NullPointerException();
      }

      priority_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Priority for the request.
     * </pre>
     *
     * <code>.google.spanner.v1.RequestOptions.Priority priority = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPriority() {

      priority_ = 0;
      onChanged();
      return this;
    }

    private Object requestTag_ = "";
    /**
     *
     *
     * <pre>
     * A per-request tag which can be applied to queries or reads, used for
     * statistics collection.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * This field is ignored for requests where it's not applicable (e.g.
     * CommitRequest).
     * `request_tag` must be a valid identifier of the form:
     * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
     * </pre>
     *
     * <code>string request_tag = 2;</code>
     *
     * @return The requestTag.
     */
    public String getRequestTag() {
      Object ref = requestTag_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        requestTag_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A per-request tag which can be applied to queries or reads, used for
     * statistics collection.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * This field is ignored for requests where it's not applicable (e.g.
     * CommitRequest).
     * `request_tag` must be a valid identifier of the form:
     * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
     * </pre>
     *
     * <code>string request_tag = 2;</code>
     *
     * @return The bytes for requestTag.
     */
    public com.google.protobuf.ByteString getRequestTagBytes() {
      Object ref = requestTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requestTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A per-request tag which can be applied to queries or reads, used for
     * statistics collection.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * This field is ignored for requests where it's not applicable (e.g.
     * CommitRequest).
     * `request_tag` must be a valid identifier of the form:
     * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
     * </pre>
     *
     * <code>string request_tag = 2;</code>
     *
     * @param value The requestTag to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTag(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      requestTag_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A per-request tag which can be applied to queries or reads, used for
     * statistics collection.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * This field is ignored for requests where it's not applicable (e.g.
     * CommitRequest).
     * `request_tag` must be a valid identifier of the form:
     * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
     * </pre>
     *
     * <code>string request_tag = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRequestTag() {

      requestTag_ = getDefaultInstance().getRequestTag();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A per-request tag which can be applied to queries or reads, used for
     * statistics collection.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * This field is ignored for requests where it's not applicable (e.g.
     * CommitRequest).
     * `request_tag` must be a valid identifier of the form:
     * `[a-zA-Z][a-zA-Z0-9_&#92;-]` between 2 and 64 characters in length
     * </pre>
     *
     * <code>string request_tag = 2;</code>
     *
     * @param value The bytes for requestTag to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTagBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      requestTag_ = value;
      onChanged();
      return this;
    }

    private Object transactionTag_ = "";
    /**
     *
     *
     * <pre>
     * A tag used for statistics collection about this transaction.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * The value of transaction_tag should be the same for all requests belonging
     * to the same transaction.
     * If this request doesn’t belong to any transaction, transaction_tag will be
     * ignored.
     * `transaction_tag` must be a valid identifier of the format:
     * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
     * </pre>
     *
     * <code>string transaction_tag = 3;</code>
     *
     * @return The transactionTag.
     */
    public String getTransactionTag() {
      Object ref = transactionTag_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transactionTag_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A tag used for statistics collection about this transaction.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * The value of transaction_tag should be the same for all requests belonging
     * to the same transaction.
     * If this request doesn’t belong to any transaction, transaction_tag will be
     * ignored.
     * `transaction_tag` must be a valid identifier of the format:
     * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
     * </pre>
     *
     * <code>string transaction_tag = 3;</code>
     *
     * @return The bytes for transactionTag.
     */
    public com.google.protobuf.ByteString getTransactionTagBytes() {
      Object ref = transactionTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        transactionTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A tag used for statistics collection about this transaction.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * The value of transaction_tag should be the same for all requests belonging
     * to the same transaction.
     * If this request doesn’t belong to any transaction, transaction_tag will be
     * ignored.
     * `transaction_tag` must be a valid identifier of the format:
     * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
     * </pre>
     *
     * <code>string transaction_tag = 3;</code>
     *
     * @param value The transactionTag to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionTag(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      transactionTag_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A tag used for statistics collection about this transaction.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * The value of transaction_tag should be the same for all requests belonging
     * to the same transaction.
     * If this request doesn’t belong to any transaction, transaction_tag will be
     * ignored.
     * `transaction_tag` must be a valid identifier of the format:
     * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
     * </pre>
     *
     * <code>string transaction_tag = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTransactionTag() {

      transactionTag_ = getDefaultInstance().getTransactionTag();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A tag used for statistics collection about this transaction.
     * Both request_tag and transaction_tag can be specified for a read or query
     * that belongs to a transaction.
     * The value of transaction_tag should be the same for all requests belonging
     * to the same transaction.
     * If this request doesn’t belong to any transaction, transaction_tag will be
     * ignored.
     * `transaction_tag` must be a valid identifier of the format:
     * [a-zA-Z][a-zA-Z0-9_&#92;-]{0,49}
     * </pre>
     *
     * <code>string transaction_tag = 3;</code>
     *
     * @param value The bytes for transactionTag to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionTagBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      transactionTag_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.spanner.v1.RequestOptions)
  }

  // @@protoc_insertion_point(class_scope:google.spanner.v1.RequestOptions)
  private static final RequestOptions DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new RequestOptions();
  }

  public static RequestOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestOptions> PARSER =
      new com.google.protobuf.AbstractParser<RequestOptions>() {
        @Override
        public RequestOptions parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestOptions(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<RequestOptions> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RequestOptions> getParserForType() {
    return PARSER;
  }

  @Override
  public RequestOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
