/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/spanner.proto

package com.google.spanner.v1;

public final class SpannerProto {
  private SpannerProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_CreateSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_CreateSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchCreateSessionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchCreateSessionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Session_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Session_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Session_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_GetSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_GetSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ListSessionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ListSessionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ListSessionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ListSessionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DeleteSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DeleteSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_RequestOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionQueryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionReadRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Partition_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Partition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ReadRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BeginTransactionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_CommitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_CommitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_RollbackRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_RollbackRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\037google/spanner/v1/spanner.proto\022\021googl"
          + "e.spanner.v1\032\034google/api/annotations.pro"
          + "to\032\027google/api/client.proto\032\037google/api/"
          + "field_behavior.proto\032\031google/api/resourc"
          + "e.proto\032\033google/protobuf/empty.proto\032\034go"
          + "ogle/protobuf/struct.proto\032\037google/proto"
          + "buf/timestamp.proto\032\027google/rpc/status.p"
          + "roto\032\034google/spanner/v1/keys.proto\032 goog"
          + "le/spanner/v1/mutation.proto\032\"google/spa"
          + "nner/v1/result_set.proto\032#google/spanner"
          + "/v1/transaction.proto\032\034google/spanner/v1"
          + "/type.proto\"~\n\024CreateSessionRequest\0229\n\010d"
          + "atabase\030\001 \001(\tB\'\340A\002\372A!\n\037spanner.googleapi"
          + "s.com/Database\022+\n\007session\030\002 \001(\0132\032.google"
          + ".spanner.v1.Session\"\251\001\n\032BatchCreateSessi"
          + "onsRequest\0229\n\010database\030\001 \001(\tB\'\340A\002\372A!\n\037sp"
          + "anner.googleapis.com/Database\0224\n\020session"
          + "_template\030\002 \001(\0132\032.google.spanner.v1.Sess"
          + "ion\022\032\n\rsession_count\030\003 \001(\005B\003\340A\002\"J\n\033Batch"
          + "CreateSessionsResponse\022+\n\007session\030\001 \003(\0132"
          + "\032.google.spanner.v1.Session\"\344\002\n\007Session\022"
          + "\014\n\004name\030\001 \001(\t\0226\n\006labels\030\002 \003(\0132&.google.s"
          + "panner.v1.Session.LabelsEntry\022/\n\013create_"
          + "time\030\003 \001(\0132\032.google.protobuf.Timestamp\022="
          + "\n\031approximate_last_use_time\030\004 \001(\0132\032.goog"
          + "le.protobuf.Timestamp\032-\n\013LabelsEntry\022\013\n\003"
          + "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:t\352Aq\n\036spann"
          + "er.googleapis.com/Session\022Oprojects/{pro"
          + "ject}/instances/{instance}/databases/{da"
          + "tabase}/sessions/{session}\"I\n\021GetSession"
          + "Request\0224\n\004name\030\001 \001(\tB&\340A\002\372A \n\036spanner.g"
          + "oogleapis.com/Session\"\207\001\n\023ListSessionsRe"
          + "quest\0229\n\010database\030\001 \001(\tB\'\340A\002\372A!\n\037spanner"
          + ".googleapis.com/Database\022\021\n\tpage_size\030\002 "
          + "\001(\005\022\022\n\npage_token\030\003 \001(\t\022\016\n\006filter\030\004 \001(\t\""
          + "]\n\024ListSessionsResponse\022,\n\010sessions\030\001 \003("
          + "\0132\032.google.spanner.v1.Session\022\027\n\017next_pa"
          + "ge_token\030\002 \001(\t\"L\n\024DeleteSessionRequest\0224"
          + "\n\004name\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis"
          + ".com/Session\"\334\001\n\016RequestOptions\022<\n\010prior"
          + "ity\030\001 \001(\0162*.google.spanner.v1.RequestOpt"
          + "ions.Priority\022\023\n\013request_tag\030\002 \001(\t\022\027\n\017tr"
          + "ansaction_tag\030\003 \001(\t\"^\n\010Priority\022\030\n\024PRIOR"
          + "ITY_UNSPECIFIED\020\000\022\020\n\014PRIORITY_LOW\020\001\022\023\n\017P"
          + "RIORITY_MEDIUM\020\002\022\021\n\rPRIORITY_HIGH\020\003\"\276\005\n\021"
          + "ExecuteSqlRequest\0227\n\007session\030\001 \001(\tB&\340A\002\372"
          + "A \n\036spanner.googleapis.com/Session\022;\n\013tr"
          + "ansaction\030\002 \001(\0132&.google.spanner.v1.Tran"
          + "sactionSelector\022\020\n\003sql\030\003 \001(\tB\003\340A\002\022\'\n\006par"
          + "ams\030\004 \001(\0132\027.google.protobuf.Struct\022I\n\013pa"
          + "ram_types\030\005 \003(\01324.google.spanner.v1.Exec"
          + "uteSqlRequest.ParamTypesEntry\022\024\n\014resume_"
          + "token\030\006 \001(\014\022B\n\nquery_mode\030\007 \001(\0162..google"
          + ".spanner.v1.ExecuteSqlRequest.QueryMode\022"
          + "\027\n\017partition_token\030\010 \001(\014\022\r\n\005seqno\030\t \001(\003\022"
          + "H\n\rquery_options\030\n \001(\01321.google.spanner."
          + "v1.ExecuteSqlRequest.QueryOptions\022:\n\017req"
          + "uest_options\030\013 \001(\0132!.google.spanner.v1.R"
          + "equestOptions\032)\n\014QueryOptions\022\031\n\021optimiz"
          + "er_version\030\001 \001(\t\032J\n\017ParamTypesEntry\022\013\n\003k"
          + "ey\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.google.spanner"
          + ".v1.Type:\0028\001\".\n\tQueryMode\022\n\n\006NORMAL\020\000\022\010\n"
          + "\004PLAN\020\001\022\013\n\007PROFILE\020\002\"\233\004\n\026ExecuteBatchDml"
          + "Request\0227\n\007session\030\001 \001(\tB&\340A\002\372A \n\036spanne"
          + "r.googleapis.com/Session\022@\n\013transaction\030"
          + "\002 \001(\0132&.google.spanner.v1.TransactionSel"
          + "ectorB\003\340A\002\022L\n\nstatements\030\003 \003(\01323.google."
          + "spanner.v1.ExecuteBatchDmlRequest.Statem"
          + "entB\003\340A\002\022\022\n\005seqno\030\004 \001(\003B\003\340A\002\022:\n\017request_"
          + "options\030\005 \001(\0132!.google.spanner.v1.Reques"
          + "tOptions\032\347\001\n\tStatement\022\013\n\003sql\030\001 \001(\t\022\'\n\006p"
          + "arams\030\002 \001(\0132\027.google.protobuf.Struct\022X\n\013"
          + "param_types\030\003 \003(\0132C.google.spanner.v1.Ex"
          + "ecuteBatchDmlRequest.Statement.ParamType"
          + "sEntry\032J\n\017ParamTypesEntry\022\013\n\003key\030\001 \001(\t\022&"
          + "\n\005value\030\002 \001(\0132\027.google.spanner.v1.Type:\002"
          + "8\001\"p\n\027ExecuteBatchDmlResponse\0221\n\013result_"
          + "sets\030\001 \003(\0132\034.google.spanner.v1.ResultSet"
          + "\022\"\n\006status\030\002 \001(\0132\022.google.rpc.Status\"H\n\020"
          + "PartitionOptions\022\034\n\024partition_size_bytes"
          + "\030\001 \001(\003\022\026\n\016max_partitions\030\002 \001(\003\"\243\003\n\025Parti"
          + "tionQueryRequest\0227\n\007session\030\001 \001(\tB&\340A\002\372A"
          + " \n\036spanner.googleapis.com/Session\022;\n\013tra"
          + "nsaction\030\002 \001(\0132&.google.spanner.v1.Trans"
          + "actionSelector\022\020\n\003sql\030\003 \001(\tB\003\340A\002\022\'\n\006para"
          + "ms\030\004 \001(\0132\027.google.protobuf.Struct\022M\n\013par"
          + "am_types\030\005 \003(\01328.google.spanner.v1.Parti"
          + "tionQueryRequest.ParamTypesEntry\022>\n\021part"
          + "ition_options\030\006 \001(\0132#.google.spanner.v1."
          + "PartitionOptions\032J\n\017ParamTypesEntry\022\013\n\003k"
          + "ey\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.google.spanner"
          + ".v1.Type:\0028\001\"\261\002\n\024PartitionReadRequest\0227\n"
          + "\007session\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleap"
          + "is.com/Session\022;\n\013transaction\030\002 \001(\0132&.go"
          + "ogle.spanner.v1.TransactionSelector\022\022\n\005t"
          + "able\030\003 \001(\tB\003\340A\002\022\r\n\005index\030\004 \001(\t\022\017\n\007column"
          + "s\030\005 \003(\t\022/\n\007key_set\030\006 \001(\0132\031.google.spanne"
          + "r.v1.KeySetB\003\340A\002\022>\n\021partition_options\030\t "
          + "\001(\0132#.google.spanner.v1.PartitionOptions"
          + "\"$\n\tPartition\022\027\n\017partition_token\030\001 \001(\014\"z"
          + "\n\021PartitionResponse\0220\n\npartitions\030\001 \003(\0132"
          + "\034.google.spanner.v1.Partition\0223\n\013transac"
          + "tion\030\002 \001(\0132\036.google.spanner.v1.Transacti"
          + "on\"\347\002\n\013ReadRequest\0227\n\007session\030\001 \001(\tB&\340A\002"
          + "\372A \n\036spanner.googleapis.com/Session\022;\n\013t"
          + "ransaction\030\002 \001(\0132&.google.spanner.v1.Tra"
          + "nsactionSelector\022\022\n\005table\030\003 \001(\tB\003\340A\002\022\r\n\005"
          + "index\030\004 \001(\t\022\024\n\007columns\030\005 \003(\tB\003\340A\002\022/\n\007key"
          + "_set\030\006 \001(\0132\031.google.spanner.v1.KeySetB\003\340"
          + "A\002\022\r\n\005limit\030\010 \001(\003\022\024\n\014resume_token\030\t \001(\014\022"
          + "\027\n\017partition_token\030\n \001(\014\022:\n\017request_opti"
          + "ons\030\013 \001(\0132!.google.spanner.v1.RequestOpt"
          + "ions\"\313\001\n\027BeginTransactionRequest\0227\n\007sess"
          + "ion\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis.co"
          + "m/Session\022;\n\007options\030\002 \001(\0132%.google.span"
          + "ner.v1.TransactionOptionsB\003\340A\002\022:\n\017reques"
          + "t_options\030\003 \001(\0132!.google.spanner.v1.Requ"
          + "estOptions\"\246\002\n\rCommitRequest\0227\n\007session\030"
          + "\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis.com/Se"
          + "ssion\022\030\n\016transaction_id\030\002 \001(\014H\000\022G\n\026singl"
          + "e_use_transaction\030\003 \001(\0132%.google.spanner"
          + ".v1.TransactionOptionsH\000\022.\n\tmutations\030\004 "
          + "\003(\0132\033.google.spanner.v1.Mutation\022:\n\017requ"
          + "est_options\030\006 \001(\0132!.google.spanner.v1.Re"
          + "questOptionsB\r\n\013transaction\"F\n\016CommitRes"
          + "ponse\0224\n\020commit_timestamp\030\001 \001(\0132\032.google"
          + ".protobuf.Timestamp\"g\n\017RollbackRequest\0227"
          + "\n\007session\030\001 \001(\tB&\340A\002\372A \n\036spanner.googlea"
          + "pis.com/Session\022\033\n\016transaction_id\030\002 \001(\014B"
          + "\003\340A\0022\300\026\n\007Spanner\022\246\001\n\rCreateSession\022\'.goo"
          + "gle.spanner.v1.CreateSessionRequest\032\032.go"
          + "ogle.spanner.v1.Session\"P\202\323\344\223\002?\":/v1/{da"
          + "tabase=projects/*/instances/*/databases/"
          + "*}/sessions:\001*\332A\010database\022\340\001\n\023BatchCreat"
          + "eSessions\022-.google.spanner.v1.BatchCreat"
          + "eSessionsRequest\032..google.spanner.v1.Bat"
          + "chCreateSessionsResponse\"j\202\323\344\223\002K\"F/v1/{d"
          + "atabase=projects/*/instances/*/databases"
          + "/*}/sessions:batchCreate:\001*\332A\026database,s"
          + "ession_count\022\227\001\n\nGetSession\022$.google.spa"
          + "nner.v1.GetSessionRequest\032\032.google.spann"
          + "er.v1.Session\"G\202\323\344\223\002:\0228/v1/{name=project"
          + "s/*/instances/*/databases/*/sessions/*}\332"
          + "A\004name\022\256\001\n\014ListSessions\022&.google.spanner"
          + ".v1.ListSessionsRequest\032\'.google.spanner"
          + ".v1.ListSessionsResponse\"M\202\323\344\223\002<\022:/v1/{d"
          + "atabase=projects/*/instances/*/databases"
          + "/*}/sessions\332A\010database\022\231\001\n\rDeleteSessio"
          + "n\022\'.google.spanner.v1.DeleteSessionReque"
          + "st\032\026.google.protobuf.Empty\"G\202\323\344\223\002:*8/v1/"
          + "{name=projects/*/instances/*/databases/*"
          + "/sessions/*}\332A\004name\022\243\001\n\nExecuteSql\022$.goo"
          + "gle.spanner.v1.ExecuteSqlRequest\032\034.googl"
          + "e.spanner.v1.ResultSet\"Q\202\323\344\223\002K\"F/v1/{ses"
          + "sion=projects/*/instances/*/databases/*/"
          + "sessions/*}:executeSql:\001*\022\276\001\n\023ExecuteStr"
          + "eamingSql\022$.google.spanner.v1.ExecuteSql"
          + "Request\032#.google.spanner.v1.PartialResul"
          + "tSet\"Z\202\323\344\223\002T\"O/v1/{session=projects/*/in"
          + "stances/*/databases/*/sessions/*}:execut"
          + "eStreamingSql:\001*0\001\022\300\001\n\017ExecuteBatchDml\022)"
          + ".google.spanner.v1.ExecuteBatchDmlReques"
          + "t\032*.google.spanner.v1.ExecuteBatchDmlRes"
          + "ponse\"V\202\323\344\223\002P\"K/v1/{session=projects/*/i"
          + "nstances/*/databases/*/sessions/*}:execu"
          + "teBatchDml:\001*\022\221\001\n\004Read\022\036.google.spanner."
          + "v1.ReadRequest\032\034.google.spanner.v1.Resul"
          + "tSet\"K\202\323\344\223\002E\"@/v1/{session=projects/*/in"
          + "stances/*/databases/*/sessions/*}:read:\001"
          + "*\022\254\001\n\rStreamingRead\022\036.google.spanner.v1."
          + "ReadRequest\032#.google.spanner.v1.PartialR"
          + "esultSet\"T\202\323\344\223\002N\"I/v1/{session=projects/"
          + "*/instances/*/databases/*/sessions/*}:st"
          + "reamingRead:\001*0\001\022\311\001\n\020BeginTransaction\022*."
          + "google.spanner.v1.BeginTransactionReques"
          + "t\032\036.google.spanner.v1.Transaction\"i\202\323\344\223\002"
          + "Q\"L/v1/{session=projects/*/instances/*/d"
          + "atabases/*/sessions/*}:beginTransaction:"
          + "\001*\332A\017session,options\022\353\001\n\006Commit\022 .google"
          + ".spanner.v1.CommitRequest\032!.google.spann"
          + "er.v1.CommitResponse\"\233\001\202\323\344\223\002G\"B/v1/{sess"
          + "ion=projects/*/instances/*/databases/*/s"
          + "essions/*}:commit:\001*\332A session,transacti"
          + "on_id,mutations\332A(session,single_use_tra"
          + "nsaction,mutations\022\260\001\n\010Rollback\022\".google"
          + ".spanner.v1.RollbackRequest\032\026.google.pro"
          + "tobuf.Empty\"h\202\323\344\223\002I\"D/v1/{session=projec"
          + "ts/*/instances/*/databases/*/sessions/*}"
          + ":rollback:\001*\332A\026session,transaction_id\022\267\001"
          + "\n\016PartitionQuery\022(.google.spanner.v1.Par"
          + "titionQueryRequest\032$.google.spanner.v1.P"
          + "artitionResponse\"U\202\323\344\223\002O\"J/v1/{session=p"
          + "rojects/*/instances/*/databases/*/sessio"
          + "ns/*}:partitionQuery:\001*\022\264\001\n\rPartitionRea"
          + "d\022\'.google.spanner.v1.PartitionReadReque"
          + "st\032$.google.spanner.v1.PartitionResponse"
          + "\"T\202\323\344\223\002N\"I/v1/{session=projects/*/instan"
          + "ces/*/databases/*/sessions/*}:partitionR"
          + "ead:\001*\032w\312A\026spanner.googleapis.com\322A[http"
          + "s://www.googleapis.com/auth/cloud-platfo"
          + "rm,https://www.googleapis.com/auth/spann"
          + "er.dataB\224\002\n\025com.google.spanner.v1B\014Spann"
          + "erProtoP\001Z8google.golang.org/genproto/go"
          + "ogleapis/spanner/v1;spanner\252\002\027Google.Clo"
          + "ud.Spanner.V1\312\002\027Google\\Cloud\\Spanner\\V1\352"
          + "\002\032Google::Cloud::Spanner::V1\352A_\n\037spanner"
          + ".googleapis.com/Database\022<projects/{proj"
          + "ect}/instances/{instance}/databases/{dat"
          + "abase}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              KeysProto.getDescriptor(),
              MutationProto.getDescriptor(),
              ResultSetProto.getDescriptor(),
              TransactionProto.getDescriptor(),
              TypeProto.getDescriptor(),
            });
    internal_static_google_spanner_v1_CreateSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_spanner_v1_CreateSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_CreateSessionRequest_descriptor,
            new String[] {
              "Database", "Session",
            });
    internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_spanner_v1_BatchCreateSessionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor,
            new String[] {
              "Database", "SessionTemplate", "SessionCount",
            });
    internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_spanner_v1_BatchCreateSessionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor,
            new String[] {
              "Session",
            });
    internal_static_google_spanner_v1_Session_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_google_spanner_v1_Session_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Session_descriptor,
            new String[] {
              "Name", "Labels", "CreateTime", "ApproximateLastUseTime",
            });
    internal_static_google_spanner_v1_Session_LabelsEntry_descriptor =
        internal_static_google_spanner_v1_Session_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_Session_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Session_LabelsEntry_descriptor,
            new String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_GetSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_spanner_v1_GetSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_GetSessionRequest_descriptor,
            new String[] {
              "Name",
            });
    internal_static_google_spanner_v1_ListSessionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_spanner_v1_ListSessionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ListSessionsRequest_descriptor,
            new String[] {
              "Database", "PageSize", "PageToken", "Filter",
            });
    internal_static_google_spanner_v1_ListSessionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_spanner_v1_ListSessionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ListSessionsResponse_descriptor,
            new String[] {
              "Sessions", "NextPageToken",
            });
    internal_static_google_spanner_v1_DeleteSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_spanner_v1_DeleteSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DeleteSessionRequest_descriptor,
            new String[] {
              "Name",
            });
    internal_static_google_spanner_v1_RequestOptions_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_RequestOptions_descriptor,
            new String[] {
              "Priority", "RequestTag", "TransactionTag",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_spanner_v1_ExecuteSqlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor,
            new String[] {
              "Session",
              "Transaction",
              "Sql",
              "Params",
              "ParamTypes",
              "ResumeToken",
              "QueryMode",
              "PartitionToken",
              "Seqno",
              "QueryOptions",
              "RequestOptions",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor =
        internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor,
            new String[] {
              "OptimizerVersion",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor.getNestedTypes().get(1);
    internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor,
            new String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor,
            new String[] {
              "Session", "Transaction", "Statements", "Seqno", "RequestOptions",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor =
        internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor,
            new String[] {
              "Sql", "Params", "ParamTypes",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor,
            new String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_spanner_v1_ExecuteBatchDmlResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor,
            new String[] {
              "ResultSets", "Status",
            });
    internal_static_google_spanner_v1_PartitionOptions_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_spanner_v1_PartitionOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionOptions_descriptor,
            new String[] {
              "PartitionSizeBytes", "MaxPartitions",
            });
    internal_static_google_spanner_v1_PartitionQueryRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_spanner_v1_PartitionQueryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionQueryRequest_descriptor,
            new String[] {
              "Session", "Transaction", "Sql", "Params", "ParamTypes", "PartitionOptions",
            });
    internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_PartitionQueryRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor,
            new String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_PartitionReadRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_spanner_v1_PartitionReadRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionReadRequest_descriptor,
            new String[] {
              "Session", "Transaction", "Table", "Index", "Columns", "KeySet", "PartitionOptions",
            });
    internal_static_google_spanner_v1_Partition_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_spanner_v1_Partition_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Partition_descriptor,
            new String[] {
              "PartitionToken",
            });
    internal_static_google_spanner_v1_PartitionResponse_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_spanner_v1_PartitionResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionResponse_descriptor,
            new String[] {
              "Partitions", "Transaction",
            });
    internal_static_google_spanner_v1_ReadRequest_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_spanner_v1_ReadRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ReadRequest_descriptor,
            new String[] {
              "Session",
              "Transaction",
              "Table",
              "Index",
              "Columns",
              "KeySet",
              "Limit",
              "ResumeToken",
              "PartitionToken",
              "RequestOptions",
            });
    internal_static_google_spanner_v1_BeginTransactionRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BeginTransactionRequest_descriptor,
            new String[] {
              "Session", "Options", "RequestOptions",
            });
    internal_static_google_spanner_v1_CommitRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_spanner_v1_CommitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_CommitRequest_descriptor,
            new String[] {
              "Session",
              "TransactionId",
              "SingleUseTransaction",
              "Mutations",
              "RequestOptions",
              "Transaction",
            });
    internal_static_google_spanner_v1_CommitResponse_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_spanner_v1_CommitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_CommitResponse_descriptor,
            new String[] {
              "CommitTimestamp",
            });
    internal_static_google_spanner_v1_RollbackRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_spanner_v1_RollbackRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_RollbackRequest_descriptor,
            new String[] {
              "Session", "TransactionId",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    KeysProto.getDescriptor();
    MutationProto.getDescriptor();
    ResultSetProto.getDescriptor();
    TransactionProto.getDescriptor();
    TypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
